### ISSUE TITLE
Having a sound component and using blip crashes the game 

### ISSUE THREAD

**Issue by wilcoverhoeven** [britzl/blip#4]
First, thank you for create a great asset :)

I'm having a problem where I'm using a sound component to play bg-music.
As soon as I call blip from a script e.g. `local hurt_sound = blip.hurt(3185);`, my game crashes.
If I remove either blip or the sound component, the games runs just file.

```
INFO:ENGINE: Defold Engine 1.2.164 (2be2687)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'

Registered lua_script_instance Extension
INFO:DLIB: SSDP: Started on address 192.168.178.16
INFO:BLIP: newSource alGenSources
ERROR:SOUND: Invalid Name
Assertion failed: (Capacity() - Size() > 0), function Push, file /Users/builder/ci/builds/engine-darwin-64-master/build/tmp/dynamo_home/sdk/include/dmsdk/dlib/array.h, line 471.
INFO:CRASH: Successfully wrote Crashdump to file: /Users/wilcoverhoeven/Library/Application Support/Defold/_crash
ERROR:CRASH: CALL STACK:

# 0 pc   0x17f1fb3d DSExternalDisplay _sigtramp+29
```

**Comment by britzl** [comment]
Hi! I'm sorry for the problems you're having. I have plans to rewrite the extension so that it doesn't conflict with OpenAL used by the engine itself.

**Comment by wilcoverhoeven** [comment]
Thank you for the reply. Ok, I understand. I will for now just use sound components for the sound effects as well , no problem.

**Comment by britzl** [comment]
Sorted now that we modify an existing sound component instead of using OpenAL direcdtly.
